version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:5.0.5-alpine

  server:
    build:
      context: ./server
    command: python taxi/manage.py runserver 0.0.0.0:8000
    container_name: server
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8001:8000

  client:
    build:
      context: ./client
    command: ng serve --host 0.0.0.0
    container_name: client
    depends_on:
      - server
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4201:4200

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - server
      - client
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

volumes:
  media:
  static: