# Generated by Django 2.2.1 on 2019-09-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='udpated',
            new_name='updated',
        ),
    ]
