# Generated by Django 2.2.4 on 2019-08-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("trips", "0002_trip")]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="drop_off_address",
            new_name="dropoff_address",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="pick_up_address",
            new_name="pickup_address",
        ),
    ]
