# Generated by Django 2.2.4 on 2019-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trips", "0004_auto_20190823_0524")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        )
    ]
